# Generated by Django 4.2.9 on 2024-02-03 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('option1', models.CharField(max_length=35)),
                ('option2', models.CharField(max_length=35)),
                ('option3', models.CharField(max_length=35)),
                ('option4', models.CharField(max_length=35)),
                ('correct', models.CharField(max_length=35)),
                ('category', models.CharField(max_length=20)),
            ],
        ),
    ]
