# Generated by Django 4.2.9 on 2024-02-03 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_question_delete_pyetje'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pyetje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pyetje', models.TextField()),
                ('option1', models.CharField(max_length=100)),
                ('option2', models.CharField(max_length=100)),
                ('option3', models.CharField(max_length=100)),
                ('option4', models.CharField(max_length=100)),
                ('correct', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name_plural': 'Pyetjet',
            },
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
