# Generated by Django 4.2.9 on 2024-02-03 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0004_pyetje_delete_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pyetje',
            name='option3',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='pyetje',
            name='option4',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
