# Generated by Django 4.2.9 on 2024-02-05 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0005_alter_pyetje_option3_alter_pyetje_option4'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pyetje',
            old_name='pyetje',
            new_name='question',
        ),
    ]
