# Generated by Django 4.2.9 on 2024-02-07 11:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('questions', '0008_kategori_alter_pyetje_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pyetje',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.kategori'),
        ),
        migrations.AlterField(
            model_name='pyetje',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
