# Generated by Django 4.2.9 on 2024-02-08 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0009_alter_pyetje_category_alter_pyetje_created_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='Progress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answered', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.pyetje')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.kategori')),
            ],
        ),
    ]
