# Generated by Django 4.2.9 on 2024-02-08 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0010_progress'),
    ]

    operations = [
        migrations.RenameField(
            model_name='progress',
            old_name='answered',
            new_name='question',
        ),
    ]
