# Generated by Django 4.2.9 on 2024-02-09 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0013_alter_kategori_options_alter_pyetje_correct_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pyetje',
            name='correct',
            field=models.CharField(max_length=255, verbose_name='Pergjigja e sakte'),
        ),
        migrations.AlterField(
            model_name='pyetje',
            name='option1',
            field=models.CharField(max_length=255, verbose_name='Opsioni 1'),
        ),
        migrations.AlterField(
            model_name='pyetje',
            name='option2',
            field=models.CharField(max_length=255, verbose_name='Opsioni 2'),
        ),
        migrations.AlterField(
            model_name='pyetje',
            name='option3',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Opsioni 3'),
        ),
        migrations.AlterField(
            model_name='pyetje',
            name='option4',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Opsioni 4'),
        ),
    ]
